//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int IdMovimiento { get; set; }
        public string CuentaOrigen { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public Nullable<long> Saldo { get; set; }
        public Nullable<long> Valor_Retiro { get; set; }
        public Nullable<long> GMF { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Banco { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Cuenta { get; set; }
    }
}
