//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int IdMovimiento { get; set; }
        public string CuentaOrigen { get; set; }
        public Nullable<long> Saldo { get; set; }
        public Nullable<long> Valor_Retiro { get; set; }
        public Nullable<long> GMF { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Tipo_Transaccion Tipo_Transaccion { get; set; }
    }
}
