//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ImportedDatabases")]
        public string DatabaseImportPath {
            get {
                return ((string)(this["DatabaseImportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ExportedDatabases")]
        public string DatabaseDownloadPath {
            get {
                return ((string)(this["DatabaseDownloadPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
        EMPRESA IDEMPRESACUENTA CONTRATOTITULAR CCTEL. FIJO BPTEL. MÓVIL BPE-MAIL BPPROVINCIAMUNICIPIODIRECCIÓN BPNOMBRE DEL CONTACTOMUNICIPIO CONTACTODIRECCIÓN CONTACTOTEL. FIJO CONTACTOTEL. MÓVIL CONTACTOE-MAIL CONTACTODIRECC. NOTIFICACIÓNID TICKET PQRORIGEN DEL TCKRADICACIÓN ESPECIALTIPO DE MATRIZEVENTOACTIVIDADCÓDIGO CAUSACAUSAFECHA RADICACIÓNTÉCNICO DE RADICACIÓNUNIDAD GENERADORAESTADOAUTORIZA RESPUESTA E-MAILUNIDAD DE ENVÍO ACTUALFECHA DE ENVÍO ACTUALFECHA FINALIZADOTÉCNICO FINALIZACIÓNUNIDAD DE ENVÍO FINALIZADORESULTADOMOTIVO DE CIERREDÍAS FINALIZACIÓNDÍAS DE GESTIÓNFECHA DEVOLUCIÓNOBSERVACIONESMARCACIÓNFECHA DE INICIO MARCACIÓNFECHA DE FIN MARCACIÓNNÚMERO DÍAS MARCACIÓN
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabaseFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>EMPRESA</string>
  <string>Póliza</string>
  <string>Nombre</string>
  <string>Telefono poliza</string>
  <string>Referencia</string>
  <string>Actividad</string>
  <string>Cod. Provincia</string>
  <string>Provincia</string>
  <string>Cod. Municipio</string>
  <string>Municipio</string>
  <string>Delegación</string>
  <string>Distrito</string>
  <string>Dirección</string>
  <string>Fecha radicación</string>
  <string>Tec. Radicación</string>
  <string>Fecha finalizado</string>
  <string>Tec. Finalización</string>
  <string>Resultado</string>
  <string>Días</string>
  <string>Origen</string>
  <string>Unidad generadora</string>
  <string>Un. Envío fin</string>
  <string>Fecha envío</string>
  <string>Usuario envío</string>
  <string>Estrato/Categ</string>
  <string>Justificado</string>
  <string>Analista</string>
  <string>Causa</string>
  <string>Fecha devolución</string>
  <string>Evento</string>
  <string>Observaciones</string>
  <string>División</string>
  <string>Marcación</string>
  <string>Día fin marcación</string>
  <string>Tel. contacto</string>
  <string>Tel. petente</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabaseFinished {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseFinished"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.80.40.245/servicios/StorageCloudServices/api/1.0")]
        public string LettersServiceURL {
            get {
                return ((string)(this["LettersServiceURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.80.40.245/servicios/ReplaceDocx/api/1.0")]
        public string ReplaceServiceURL {
            get {
                return ((string)(this["ReplaceServiceURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1CfhzXbfDAL3WQ8O-u3uxhabEhYsbJSno")]
        public string IdDocumentModel {
            get {
                return ((string)(this["IdDocumentModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AV_AppAuthorization QzVFMjcyNEItNUUxOC00RTAwLTg5RTktMzQ3REU1RUQ2MEUz")]
        public string AuthorizationBPMLetters {
            get {
                return ((string)(this["AuthorizationBPMLetters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AV_AppAuthorization ZTNhOWUyYTItZjc0Ny00NjU4LWI4MGYtYTYxMTllMjg5MzIz")]
        public string AuthorizationTemplates {
            get {
                return ((string)(this["AuthorizationTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://181.143.170.107:8089/BPM/PrintService/api/")]
        public string PrintingServiceURL {
            get {
                return ((string)(this["PrintingServiceURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Referencia</string>\r\n  <string>Division</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LotFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LotFields"]));
            }
        }
    }
}
